POST http://localhost:3000/api/v1/users/signup
Content-Type: application/json

{
    "username": "bachi1r",
    "email": "bachi1r@gmail.b",
    "password": "YOOBROW12"
}
###

POST http://localhost:3000/api/v1/users/token
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImJhY2hpciIsImlhdCI6MTc1OTY5NzE0OH0.z_IjfEcUMo6EHswsquaxqlprF0fMCsdk8OwrkPRYW-8"
}

###

GET http://localhost:3000/api/v1/users/temp
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImJhY2hpciIsImlhdCI6MTc1OTY5NzIxNywiZXhwIjoxNzU5Njk3MjMyfQ.2QEb8V14-3l0JJgmCAHqZLw3CxQW7HG1vgqfodNNeoM